// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivabirwuxxuetnvitxzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2YWJpcnd1eHh1ZXRudml0eHpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTYyMzIsImV4cCI6MjA2MTc3MjIzMn0.-5qnGihsI7HqSwJQnkozQaHO5jw2Mx-U6OuqoLzwYPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);